
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Nov 07 17:01:49 CET 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBOXBR = 10;
  public static final int CHAR = 50;
  public static final int CONST = 5;
  public static final int LESSE = 37;
  public static final int RBOXBR = 11;
  public static final int PLUS_ASSIGN = 42;
  public static final int GRT = 34;
  public static final int NOT_EQUAL = 33;
  public static final int LPAREN = 12;
  public static final int SEMI = 6;
  public static final int CONTINUE = 19;
  public static final int LESS = 36;
  public static final int FOR = 15;
  public static final int MINUS = 29;
  public static final int RPAREN = 13;
  public static final int AND = 27;
  public static final int OR = 28;
  public static final int BOOL = 49;
  public static final int COMMA = 8;
  public static final int CLASS = 22;
  public static final int INC = 25;
  public static final int DIV = 40;
  public static final int PLUS = 38;
  public static final int ASSIGN = 7;
  public static final int IF = 16;
  public static final int DOT = 31;
  public static final int ABSTRACT = 24;
  public static final int EOF = 0;
  public static final int RETURN = 17;
  public static final int GRTE = 35;
  public static final int EQUAL = 32;
  public static final int NEW = 30;
  public static final int error = 1;
  public static final int MUL = 39;
  public static final int NUMBER = 47;
  public static final int MOD = 41;
  public static final int IDENT = 48;
  public static final int BREAK = 18;
  public static final int VOID = 9;
  public static final int MOD_ASSIGN = 46;
  public static final int DIV_ASSIGN = 45;
  public static final int LBRACE = 3;
  public static final int ELSE = 14;
  public static final int READ = 20;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 23;
  public static final int PROG = 2;
  public static final int MUL_ASSIGN = 44;
  public static final int DEC = 26;
  public static final int MINUS_ASSIGN = 43;
  public static final int PRINT = 21;
}

